//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduFeedback.Core.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course_Master()
        {
            this.Course_Purchase = new HashSet<Course_Purchase>();
            this.TransactionLogs = new HashSet<TransactionLogs>();
        }
    
        public int Course_ID { get; set; }
        public string Course_Name { get; set; }
        public string Short_Desc { get; set; }
        public string Course_Desc { get; set; }
        public Nullable<decimal> Course_Fee { get; set; }
        public string Course_Tag { get; set; }
        public Nullable<int> Subject_ID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> CourseType { get; set; }
        public Nullable<int> Year_ID { get; set; }
        public string Product_ID { get; set; }
        public Nullable<int> Organisation_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_Purchase> Course_Purchase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionLogs> TransactionLogs { get; set; }
    }
}
