//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduFeedback.Core.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_Purchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course_Purchase()
        {
            this.TransactionLogs = new HashSet<TransactionLogs>();
        }
    
        public int Log_ID { get; set; }
        public Nullable<int> Parent_ID { get; set; }
        public Nullable<int> Course_ID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Status { get; set; }
        public Nullable<int> AssignmentPerWeek { get; set; }
        public Nullable<int> CourseType { get; set; }
        public string Promo_ID { get; set; }
        public string Subscription_ID { get; set; }
        public Nullable<int> DefaultYear_ID { get; set; }
        public Nullable<int> L2w_pcm_id { get; set; }
        public Nullable<int> Gcse_pcm_id { get; set; }
        public string TxnClient { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> Mutli_Purchase_ID { get; set; }
    
        public virtual Course_Master Course_Master { get; set; }
        public virtual Registration Registration { get; set; }
        public virtual SchoolYear SchoolYear { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionLogs> TransactionLogs { get; set; }
    }
}
