//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduFeedback.Core.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailContent
    {
        public int Content_ID { get; set; }
        public string ContentName { get; set; }
        public string ContentCode { get; set; }
        public string Action { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public string Footer { get; set; }
    }
}
