//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduFeedback.Core.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feature_ROLE_MAP
    {
        public int ID { get; set; }
        public int FeatureID { get; set; }
        public int RoleID { get; set; }
    
        public virtual Feature Feature { get; set; }
        public virtual Role Role { get; set; }
    }
}
