//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduFeedback.Core.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organisation
    {
        public int Organisation_ID { get; set; }
        public string OrganisationName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string EmailContact { get; set; }
        public string EmailCode { get; set; }
        public string WebsiteUrl { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> Org_ID { get; set; }
        public Nullable<bool> IsExternalClient { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string OrganisationType { get; set; }
        public bool StudentNameMapping { get; set; }
    }
}
