//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduFeedback.Core.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promo_Master
    {
        public int PromoID { get; set; }
        public int CourseID { get; set; }
        public string Promo_Code { get; set; }
        public int Discount_Percent { get; set; }
        public decimal Discount_Flat { get; set; }
        public System.DateTime Start_Date { get; set; }
        public System.DateTime Ending_Date { get; set; }
        public int Is_Active { get; set; }
        public string Discount_Type { get; set; }
    }
}
