//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduFeedback.Core.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Registration()
        {
            this.ROLE_USER_MAP = new HashSet<ROLE_USER_MAP>();
        }
    
        public int User_ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email_ID { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string UserName { get; set; }
        public string Type { get; set; }
        public Nullable<int> Capacity { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<int> Year_ID { get; set; }
        public string RegisteredFrom { get; set; }
        public Nullable<int> OrgnKey { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string ClientUser_ID { get; set; }
    
        public virtual SchoolYear SchoolYear { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ROLE_USER_MAP> ROLE_USER_MAP { get; set; }
    }
}
