//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduFeedback.Core.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionLogs
    {
        public int ID { get; set; }
        public Nullable<int> Log_ID { get; set; }
        public Nullable<int> Parent_ID { get; set; }
        public Nullable<int> Course_ID { get; set; }
        public string Name { get; set; }
        public string PaymentStatus { get; set; }
        public string PayerEmail { get; set; }
        public string TxnType { get; set; }
        public string TxnId { get; set; }
        public Nullable<decimal> mc_gross { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string SubscriptionId { get; set; }
        public string CardName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Installments { get; set; }
        public string InvoiceId { get; set; }
        public string InvoiceUrl { get; set; }
        public string TokenID { get; set; }
        public string CustomerID { get; set; }
        public string Description { get; set; }
    }
}
